name: CI

on:
  pull_request:

  workflow_dispatch:

jobs:
  lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: pnpm
      - name: pnpm ci
        run: pnpm ci
      - name: run lint
        run: pnpm run lint
      - name: run typecheck
        run: pnpm run typecheck
